### ISSUE TITLE
Cassandra 재설치

### ISSUE THREAD

**Issue by CyanRYi** [seminar-booking/booking#4]
사실 Cassandra를 재설치할 필요는 없지만,

cassandra가 JDK8u152 이상의 버전에서는 현재 오류가 있는 상황이므로

최초프로세스부터 다시 실행한다.

@virustaruin 테스트 안했냐................안올라와있드만............

**Comment by CyanRYi** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-14173
fix는 됐다는데 3.11.2가 아직 릴리즈 안됐다 카더라 -

**Comment by CyanRYi** [comment]
* sudo yum update
* sudo yum remove java*
* wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
* sudo rpm -ivh jdk-8u131-linux-x64.rpm
* sudo vi /etc/profile에 추가
JAVA_HOME=/usr/java/jdk1.8.0_131
export JAVA_HOME
PATH=$JAVAHOME/bin:$PATH
export PATH
* sudo vi /etc/yum.repos.d/cassandra.repo
[cassandra]
name=Apache Cassandra
baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://www.apache.org/dist/cassandra/KEYS
추가
* sudo yum install cassandra
* sudo chown -R ec2-user:ec2-user /var/lib/cassandra
* sudo chown -R ec2-user:ec2-user /var/log/cassandra
* sudo vi /etc/cassandra/conf/cassandra.yaml
rpc_address를 localhost에서 0.0.0.0으로, broadcast_rpc_address를 주석해제하여 localhost로.
(외부 접속을 위함)

**Comment by kwanghan-bae** [comment]
JDK8u152  < 이 친구는 문제가 많네요.
Soap 관련해서도 버그가 있어서 T사에서 문제 발생한적 있는데 😞

**Comment by CyanRYi** [comment]
아니 그녀석은 문제 없고 걔 뒤에서 문제
